import styles from "../styles/About.module.scss";
import Head from "next/head";
import {Row} from "antd";
import SectionOne from "@/components/sectionOne";
import SectionTwo from "@/components/sectionTwo";

export default function Aboutus() {
    return (
        <>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Row className={styles.container}>
                <div className={styles.section}>
                    <h1 className={styles.label}>About Us</h1>
                    <p className={styles.description}>A team of architects, engineers, contractors and technologists
                        driven by the desire to create a waste free future and a custom made world.
                    </p>
                    <img className={styles.mainImage} src={"/team1.png"}/>
                </div>
                <div className={styles.section}>
                    <h1 className={styles.label}>Our Mission</h1>
                    <p className={styles.description}>It is our goal to bring unity, understanding
                        mutual goals and rewards shared responsibility
                        to the entirety of the design and construction process
                    </p>
                </div>
                <SectionTwo image={"/team2.png"} mainText={"For the new wave of proptech pioneers."} subText={""}/>
                <div className={styles.section}>
                    <h1 className={styles.label}>Team</h1>
                    <p className={styles.description}>Meet the people behind our magical product</p>
                </div>
                <div className={styles.section}>
                    <img className={styles.fullTeam} src={"/fullteam.png"}/>
                </div>
            </Row>
        </>
    )
}