import Head from "next/head";
import SectionOne from "@/components/sectionOne";
import SectionTwo from "@/components/sectionTwo";
import SectionThree from "@/components/sectionThree";
import SectionFour from "@/components/sectionFour";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import styles from "@/components/form/form.module.scss";
import TextField from "@mui/material/TextField";
import Button from "@mui/material/Button";
import React from "react";

export default function Contactus() {
    const [fullName, setFullName] = React.useState("");
    const [email, setEmail] = React.useState("");
    const [jobTitle, setJobTitle] = React.useState("");
    const [error, setError] = React.useState(false);

    return (
        <div className={"contactUs"}>
            <Head>
                <title>Contact Us</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Grid container rowSpacing={1}
                  columnSpacing={{ xs: 1, sm: 2, md: 3 }}>
                <Grid item xs={12} sm={6}>
                    <Box component="img" src={"contactus.png"} className={"image"} />
                </Grid>
                <Grid item xs={12} sm={6}>
                    <Box style={{
                        backgroundColor: "#fff",
                        padding: "2rem",
                        borderRadius: "13px",
                        margin: "2rem"
                    }}>
                    <h1>Contact Us</h1>
                    <p>Explore the future of AEC with us.<br/>Feel free to get in touch.</p>
                    <form onSubmit={() => {}} className={styles.form}>
                        <TextField
                            required
                            label="Full Name"
                            value={fullName}
                            onChange={(e) => setFullName(e.target.value)}
                            className={styles.name}
                        />
                        <TextField
                            label="Job Title"
                            value={jobTitle}
                            onChange={(e: any) => setJobTitle(e.target.value)}
                            className={styles.jobTitle}
                        />
                        <TextField
                            required
                            label="Email"
                            value={email}
                            onChange={(e: any) => setEmail(e.target.value)}
                            className={styles.email}
                        />
                        <Button type="submit" className={styles.submit}>
                            Send Message
                        </Button>
                    </form>
                    </Box>
                </Grid>
            </Grid>
        </div>
    )
}