import Head from "next/head";
import SectionOne from "@/components/sectionOne";
import SectionTwo from "@/components/sectionTwo";
import SectionThree from "@/components/sectionThree";
import SectionFour from "@/components/sectionFour";

export default function Contactus() {
    return (
        <>
            <Head>
                <title>Contact Us</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
        </>
    )
}