import Head from 'next/head'
import SectionTwo from "@/components/sectionTwo";
import SectionOne from "@/components/sectionOne";
import SectionThree from "@/components/sectionThree";
import SectionFour from "@/components/sectionFour";
import HeaderBanner from "@/components/HeaderBanner";
import styles from "@/components/HeaderBanner/headerBanner.module.scss";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import React from "react";

const sectionOneProps = {
    image: "/logo.png",
    mainText: "Designing a waste free, custom made world of AEC",
    subText: "A blockchain solution that provides a shared, seamless space to bring everyone onto the same page",
    withDownloadButton: true
}

const sectionTwoProps = {
    image: "/logo.png",
    mainText: "AEC is hyper wasteful. Our mission is waste-free construction.",
    subText: "a platform that coordinates and automates the transactional activities of the AEC industry, securely validating the process whilst optimising outcomes."
}

const sectionThreeProps = {
    image: "/img2.png",
    mainText: "closer connections, smoother handovers, greater precision.",
}

const sectionFourProps = {
    image: "/img4.png",
    mainText: "a digital twin with representing the entire design and construction process visually",
}

export default function Home() {
    return (
        <>
            <Head>
                <title>Bohm</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="stylesheet"
                      href="https://fonts.googleapis.com/css?family=Roboto" />
            </Head>
            <HeaderBanner style={{height: "100vh"}} {...sectionOneProps}/>

            <Grid container className={"tileContainer1"} style={{
                paddingTop: "4rem"
            }}>
                <Grid item xs={8} sm={4} className={"gridA"}>
                    <Box component="img" src={"tile1.png"} className={"tileImageContainer"} />
                </Grid>
                <Grid item xs={12} sm={6} style={{
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "flex-end",
                    paddingBottom: "5rem",
                    color: "black"
                }}>
                    <div style={{
                        display: "flex",
                        justifyContent: "flex-start",
                        fontSize: "2.5rem"
                    }}>
                    <span style={{
                        fontWeight: "bold"
                    }}>AEC</span> <span style={{
                        marginLeft: "0.5rem",
                        marginRight: "0.5rem",
                        fontWeight: "lighter",
                    }}>is </span><p style={{
                        fontWeight: "bold"
                    }}>hyper wasteful</p>
                    </div>
                </Grid>
            </Grid>

            <Grid container className={"tileContainer2"}>
                <Grid item xs={12} sm={6} className={"gridA"}>
                    <Box component="img" src={"tile2.png"} style={{
                        width: "50%",
                        height: "100%"
                    }} className={styles.tileImageContainer} />
                </Grid>
                <Grid item xs={12} sm={6}
                      sx={{ alignItems: { xs: 'center' } }}
                      style={{
                          display: "flex",
                          flexDirection: "column",
                          justifyContent: "flex-end",
                          paddingBottom: "2rem",
                          color: "black",
                          fontSize: "3rem"
                      }}>
                    <p>our mission is<br/>waste-free<br/>construction</p>
                </Grid>
            </Grid>

            <Grid container className={"tileContainer3"}>
                <Grid item xs={12} sm={7}
                      sx={{paddingRight: {xs: '1rem'}}}
                      style={{
                          display: "flex",
                          flexDirection: "row",
                          justifyContent: "flex-end",
                          paddingBottom: "2rem",
                          color: "black",
                          fontSize: "1.5rem",
                          alignItems: "flex-end"
                      }}>
                    <p>a platform that coordinates<br/>
                        and automates the transactional<br/>
                        activities of the AEC industry<br/>
                        <br/>
                        securely validating the process<br/>
                        whilst optimising outcomes
                    </p>
                </Grid>
                <Grid item xs={12} sm={5}
                      sx={{paddingLeft: {xs: '5rem'}}}
                      style={{
                          display: "flex",
                          justifyContent: "flex-start",
                      }}>
                    <Box component="img" src={"tile3.png"} style={{
                        width: "60%",
                        height: "100%",
                    }} className={"tileImageContainer"} />
                </Grid>
            </Grid>
            <SectionThree {...sectionThreeProps} />
            <SectionFour {...sectionFourProps} />
        </>
    )
}
