import Head from 'next/head'
import HeaderBanner from "@/components/HeaderBanner";
import React from "react";
import AeCSection from "@/components/AeCSection";
import TriangleInfoSection from "@/components/TriangleInfoSection";

export default function Home() {
    return (
        <>
            <Head>
                <title>Bohm</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins" />
                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter" />
            </Head>
            <HeaderBanner />
            <AeCSection />
            <TriangleInfoSection />
        </>
    )
}
