import Head from 'next/head'
import SectionTwo from "@/components/sectionTwo";
import SectionOne from "@/components/sectionOne";
import SectionThree from "@/components/sectionThree";
import SectionFour from "@/components/sectionFour";
import HeaderBanner from "@/components/HeaderBanner";
import styles from "@/components/HeaderBanner/headerBanner.module.scss";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import React from "react";

const sectionOneProps = {
    image: "/logo.png",
    mainText: "Designing a waste free, custom made world of AEC",
    subText: "A blockchain solution that provides a shared, seamless space to bring everyone onto the same page",
    withDownloadButton: true
}

const sectionTwoProps = {
    image: "/logo.png",
    mainText: "AEC is hyper wasteful. Our mission is waste-free construction.",
    subText: "a platform that coordinates and automates the transactional activities of the AEC industry, securely validating the process whilst optimising outcomes."
}

const sectionThreeProps = {
    image: "/img2.png",
    mainText: "closer connections, smoother handovers, greater precision.",
}

const sectionFourProps = {
    image: "/img4.png",
    mainText: "a digital twin with representing the entire design and construction process visually",
}

export default function Home() {
    return (
        <>
            <Head>
                <title>Bohm</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="stylesheet"
                      href="https://fonts.googleapis.com/css?family=Roboto" />
            </Head>
            <HeaderBanner style={{height: "100vh"}} {...sectionOneProps}/>

            <Grid container className={"tileContainer1"} style={{
                paddingTop: "4rem"
            }}>
                <Grid item xs={8} sm={4} className={"gridA"}>
                    <Box component="img" src={"tile1.png"} className={"tileImageContainer"} />
                </Grid>
                <Grid item xs={12} sm={6} style={{
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "flex-end",
                    paddingBottom: "5rem",
                    color: "black"
                }}
                      sx={{
                          fontSize: {"xs": "1.2rem"},
                          justifyContent: {xs: 'center'}
                      }}
                >
                    <div style={{
                        display: "flex",
                        justifyContent: "flex-start",
                    }}>
                    <p style={{
                        marginLeft: "0.5rem",
                        marginRight: "0.5rem",
                        fontWeight: "lighter",
                    }}>The AEC industry and the built<br/>
                        environment is responsible for<br/>
                        nearly 40% of global </p>
                    </div>
                </Grid>
            </Grid>

            <Grid container className={"tileContainer2"}>
                <Grid item xs={12} sm={6} className={"gridA"}>
                    <Box component="img" src={"tile2.png"} style={{
                        width: "50%",
                        height: "100%"
                    }} className={styles.tileImageContainer} />
                </Grid>
                <Grid item xs={12} sm={6}
                      sx={{ alignItems: { xs: 'center' }, fontSize: {"xs": "1.2rem", "sm": "1.5rem"},
                          justifyContent: {xs: 'center'} }}
                      style={{
                          display: "flex",
                          flexDirection: "column",
                          justifyContent: "flex-end",
                          paddingBottom: "2rem",
                          color: "black",
                          fontWeight: "lighter",
                      }}>
                    <p>Communication between<br/> AEC disciplines is<br/> fragmented & ineffective</p>
                </Grid>
            </Grid>

            <Grid container className={"tileContainer3"}>
                <Grid item xs={12} sm={7}
                      sx={{paddingRight: {xs: '1rem'}, justifyContent: {xs: 'center', sm: 'flex-end'}}}
                      style={{
                          display: "flex",
                          flexDirection: "row",
                          paddingBottom: "2rem",
                          color: "black",
                          fontSize: "1.2rem",
                          alignItems: "flex-end",
                          fontWeight: "lighter",
                      }}>
                    <p>Procurement of <br/>goods and services<br/> is wasteful, costly<br/> and prone to error
                    </p>
                </Grid>
                <Grid item xs={12} sm={5}
                      sx={{paddingLeft: {xs: '5rem'}}}
                      style={{
                          display: "flex",
                          justifyContent: "flex-start",
                      }}>
                    <Box component="img" src={"tile3.png"} style={{
                        width: "60%",
                        height: "100%",
                    }} className={"tileImageContainer"} />
                </Grid>
            </Grid>
            <Grid container>
            <Grid item xs={20} sm={12}
                  sx={{paddingLeft: {xs: '5rem'}, justifyContent: {xs: 'flex-start', sm: 'center'}}}
                  style={{
                      display: "flex",
                      fontSize: "1.5rem",
                      paddingTop: "5rem"
                  }}>
                <p style={{
                    width: "80%",
                }}>By intelligently connecting all parties in any architectural and
                    construction process, BOHM ensures smooth handovers, mutual goals and united conversations.
                    Time, resources and money are optimised and the entire chain is underpinned by
                    efficiency and transparency. Commercial and environmental goals operate in support of one
                    another and what would have been waste becomes profit.</p>
            </Grid>
                <Grid container style={{
                    padding: "5rem"
                }}
                        sx={{paddingLeft: {xs: 0},
                            justifyContent: {xs: 'flex-start'}
                }}
                >
                <Grid item xs={12} sm={6} style={{
                    display: "flex",
                    justifyContent: "flex-end",
                }}>
                    <Box component="img" src={"triangle.png"} className={"tileImageContainer"}
                         sx={{
                             width: {xs: "100% !important", sm: "50% !important", md: "50% !important", lg: "50% !important"},
                             paddingBottom: {xs: "2rem", sm: "0rem", md: "0rem", lg: "0rem"},
                         }}/>
                </Grid>
                <Grid item xs={12} sm={6} style={{
                    display: "flex",
                    justifyContent: "flex-end",
                }}>
                    <Box component="img" src={"triangle.png"} className={"tileImageContainer"}
                         sx={{
                             width: {xs: "100% !important", sm: "50% !important", md: "50% !important", lg: "50% !important"},
                         }}
                    />
                </Grid>
                </Grid>
            </Grid>
            <Grid container style={{
                float: "right",
                padding: "4rem"
            }} sx={{
                justifyContent: {xs: 'center', sm: 'flex-end'},
                paddingLeft: {xs: '0rem !important'},
                width: {xs: "100% !important", sm: "80% !important", md: "80% !important", lg: "80% !important"}
            }}>
                <Grid item xs={24} sm={12} sx={{paddingLeft: {xs: '5rem'}}}
                      style={{
                          display: "flex",
                          fontSize: "2rem"
                      }}>
                    <p>BOHM automates the transactional activities of the AEC industry
                        <br/><br/> Securely validating process and optimising outcomes</p>
                </Grid>
            </Grid>
        </>
    )
}
