import styles from "../styles/Lean.module.scss";
import Head from "next/head";
import {Row} from "antd";
import SectionOne from "@/components/sectionOne";

export default function LeanConstruction() {
    return (
        <>
            <Head>
                <title>Lean Construction</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Row className={styles.leanContainer}>
                <SectionOne style={{
                    width: "100vw",
                    height: "100vh",
                }} image={"/leanCanvas/img1.jpg"} mainText={"Lean Construction"} subText={"" +
                    "The future of construction holds immense promise with the adoption of Lean principles. By prioritizing efficiency, reducing waste, and putting people first, we can build a more sustainable and equitable world for all."} />
                <div className={styles.image}>
                    <img src={"/leanCanvas/img2.png"}/>
                </div>
                <div className={styles.image}>
                    <img src={"/leanCanvas/img3.png"}/>
                </div>
                <div className={styles.image}>
                    <img src={"/leanCanvas/img4.png"}/>
                </div>
                <div className={styles.image}>
                    <img src={"/leanCanvas/img5.png"}/>
                </div>
                <div className={styles.image}>
                    <img src={"/leanCanvas/img6.png"}/>
                </div>
                <div className={styles.image}>
                    <img src={"/leanCanvas/img7.png"}/>
                </div>
                <div className={styles.image}>
                    <img src={"/leanCanvas/img8.png"}/>
                </div>
                <div className={styles.image}>
                    <img src={"/leanCanvas/img9.png"}/>
                </div>
            </Row>
        </>
    )
}